<?php

$womanTables = $this->getCollectionByParent($this->womanId);
$manTables = $this->getCollectionByParent($this->manId);
$kidsTables = $this->getCollectionByParent($this->kidsId);

?>

<div id="sizeguide" class="std">
    <div class="narrow-frame">
        <h2 class="title-sm"><?php echo $this->__('Size guide'); ?>!</h2>
        <p class="text"><?php echo $this->__('Please note that this table is meant to be used as a guide only.<br>Sizes may vary notably between different clothing manufacturers & brands.'); ?></p>
        <?php if ($womanTables || $manTables || $kidsTables) : ?>
            <div class="tabs">
                <ul class="tabs-nav">
                    <?php if($womanTables) : ?>
                        <li class="title" data-id="sizeguide-women">
                            <a href="#tab-women"><?php echo $this->__('Women'); ?></a>
                        </li>
                    <?php endif; ?>
                    <?php if($manTables) : ?>
                        <li class="title" data-id="sizeguide-men">
                            <a href="#tab-men"><?php echo $this->__('Men'); ?></a>
                        </li>
                    <?php endif; ?>
                    <?php if($kidsTables) : ?>
                        <li class="title" data-id="sizeguide-kids">
                            <a href="#tab-kids"><?php echo $this->__('Kids'); ?></a>
                        </li>
                    <?php endif; ?>
                </ul>
                <div class="tabs-content accordion">
                    <?php if($womanTables) : ?>
                        <div class="title toggle mobile-only"><?php echo $this->__('Women') ?></div>
                        <div id="tab-women">
                            <div class="single-accordion acc-closed acc-slow acc-mobile" id="sizeguide-women">
                                <?php foreach ( $womanTables as $item ) : ?>
                                    <p class="title"><?php echo $item->getName(); ?></p>
                                    <div class="table-wrapper"><?php echo $item->getTable(); ?></div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if($manTables) : ?>
                        <div class="title mobile-only"><?php echo $this->__('Men') ?></div>
                        <div id="tab-men">
                            <div class="single-accordion acc-closed acc-slow acc-mobile" id="sizeguide-men">
                                <?php foreach ( $manTables as $item ) : ?>
                                    <p class="title"><?php echo $item->getName(); ?></p>
                                    <div class="table-wrapper"><?php echo $item->getTable(); ?></div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if($kidsTables) : ?>
                        <div class="title mobile-only"><?php echo $this->__('Kids') ?></div>
                        <div id="tab-kids">
                            <div class="single-accordion acc-closed acc-slow acc-mobile" id="sizeguide-kids">
                                <?php foreach ( $kidsTables as $item ) : ?>
                                    <p class="title"><?php echo $item->getName(); ?></p>
                                    <div class="table-wrapper"><?php echo $item->getTable(); ?></div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
