<?php $sizetables = $this->getSizetablesCollection(); ?>

<h1 class="page-title cms-title left-side blue-bg sizeguide-title">
    <div class="narrow-frame cms-frame"><?php echo $this->__('Size guide'); ?></div>
</h1>

<div id="sizeguide" class="std">
    <div class="narrow-frame">
        <p class="text"><?php echo $this->__('Please note that this table is meant to be used as a guide only.<br>Sizes may vary notably between different clothing manufacturers & brands.'); ?></p>
        <div class="tabs">
            <ul class="tabs-nav">
                <?php if($this->_isWoman()) : ?>
                    <li class="title" data-id="sizeguide-women">
                        <a href="#tab-women"><?php echo $this->__('Women'); ?></a>
                    </li>
                <?php endif; ?>
                <?php if($this->_isMan()) : ?>
                    <li class="title" data-id="sizeguide-men">
                        <a href="#tab-men"><?php echo $this->__('Men'); ?></a>
                    </li>
                <?php endif; ?>
                <?php if($this->_isKids()) : ?>
                    <li class="title" data-id="sizeguide-kids">
                        <a href="#tab-kids"><?php echo $this->__('Kids'); ?></a>
                    </li>
                <?php endif; ?>
            </ul>
            <div class="tabs-content accordion">
                <?php if($this->_isWoman()) : ?>
                    <div class="title toggle mobile-only"><?php echo $this->__('Women') ?></div>
                    <div id="tab-women">
                        <div class="single-accordion acc-closed acc-slow acc-mobile" id="sizeguide-women">
                            <?php foreach ( $sizetables as $item ) : ?>
                                <?php if ($item->getParent() == Mage::getStoreConfig($this->_womanId)) : ?>
                                <p class="title"><?php echo $item->getName(); ?></p>
                                <div class="table-wrapper"><?php echo $item->getTable(); ?></div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if($this->_isMan()) : ?>
                    <div class="title mobile-only"><?php echo $this->__('Men') ?></div>
                    <div id="tab-men">
                        <div class="single-accordion acc-closed acc-slow acc-mobile" id="sizeguide-men">
                            <?php foreach ( $sizetables as $item ) : ?>
                                <?php if ($item->getParent() == Mage::getStoreConfig($this->_manId)) : ?>
                                <p class="title"><?php echo $item->getName(); ?></p>
                                <div class="table-wrapper"><?php echo $item->getTable(); ?></div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if($this->_isKids()) : ?>
                    <div class="title mobile-only"><?php echo $this->__('Kids') ?></div>
                    <div id="tab-kids">
                        <div class="single-accordion acc-closed acc-slow acc-mobile" id="sizeguide-kids">
                            <?php foreach ( $sizetables as $item ) : ?>
                                <?php if ($item->getParent() == Mage::getStoreConfig($this->_kidsId)) : ?>
                                <p class="title"><?php echo $item->getName(); ?></p>
                                <div class="table-wrapper"><?php echo $item->getTable(); ?></div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
